### PR TITLE
Add a Dockerfile to cache dependencies use in the main repo in an image

### PR DESCRIPTION
**Pull request by a-magdy**
Add Dockerfile-deps-cache to cache dependencies used in the main repo in a docker image, speeding up build time

The idea here, is to create an empty go file, with all the dependencies used in the main repo, speeding up build times (will be used mostly in CI)

If you agree on the idea of this, we'll need to configure automate build for it as well

I didn't want to merge this to master, without discussing the idea itself, and whether you want it in either another branch or maybe another repo

The `rwynn/monstache-builder` took one step out of the multi-stage build in the main repo, I think this could take another step out, and make the main build even smaller, it could be called `rwynn/monstache-builder-with-cache` or `rwynn/monstache-builder-cache`

### CODE REVIEW

**Comment by rwynn** [comment]
This is a great idea.  I think we should use branches for each cached image (that seems to go well with how the automated builds work).  We will need one branch with the .go file you have here, and another branch with the same .go file name but different dependencies for monstache rel3.  See the monstache.go file in the rel3 branch for that list.

**Comment by rwynn** [comment]
Heres the link to the rel3 version with its depends.

https://github.com/rwynn/monstache/blob/rel3/monstache.go

**Comment by rwynn** [comment]
@a-magdy I added 2 branches based on this PR and added automated builds for each branch.

**Comment by a-magdy** [comment]
Great, thanks, I think we can close this PR now :+1: 

Links to the generated docker image for future readers: 

Latest (Monstache v4): https://hub.docker.com/r/rwynn/monstache-builder-cache/
(Monstache v3 -for Elasticsearch < 6-)https://hub.docker.com/r/rwynn/monstache-builder-cache-rel3/

**Pull request closed without merging**
